<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x64</Platforms>
	</PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Execute.png" />
    <None Remove="Resources\Search.png" />
  </ItemGroup>
    <ItemGroup>
    <!-- These lines tell the project where to find the Revit API libraries -->
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2023\RevitAPI.dll</HintPath>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2023\RevitAPIUI.dll</HintPath>
    </Reference>
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
    <ItemGroup>
      <None Update="MyRevitAddin.addin">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <ItemGroup>
      <EmbeddedResource Include="Resources\Icons\Execute.png" />
      <EmbeddedResource Include="Resources\Icons\Search.png" />
    </ItemGroup>
</Project>
